#ifndef _ITEM_H_
#define _ITEM_H_

enum ITEM_IDX
{
	IWOODEN_SWORD = 0,
	IHAMMER = 1,
	IGIANT_HAMMER = 2,
	IMAGIC_WAND = 3,
	IRITUAL_SWORD = 4,
	IWOODEN_SHIELD = 5,
	IPLATE_ARMOR = 6,
	ILEATHER_ARMOR = 7,
	IROBE = 8,
	ILAUREL_WREATH = 9,
	IHOLY_GRAIL = 10,
	ISHOES = 11,
	IBRACELET = 12,
	IGODSBEARD = 13,
	IGOLDEN_ROOT = 14,
	ITELEPORT_SCROLL = 15,
	ITENT = 16
};

#endif // _ITEM_H_
